# Generated by Django 5.2.2 on 2025-06-22 13:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('pros', models.TextField(blank=True, verbose_name='pros')),
                ('cons', models.TextField(blank=True, verbose_name='cons')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='status')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='moderator comment')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='not helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
